### ISSUE TITLE
Issues with deployment onto conda channel

### ISSUE THREAD

**Issue by csyhuang** [csyhuang/hn2016_falwa#77]
So far, deployment onto pip/conda channel has not been successful yet.

Here is what I tried for conda deployment.

My build.sh:
```bash
$PYTHON setup.py install
```

My meta.yaml
```yml
{% set name = "hn2016_falwa" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/csyhuang/hn2016_falwa

requirements:
  build:
    - python
    - numpy==1.22.3    
    - setuptools
  run:
    - python

test:
  imports:
    - hn2016_falwa

about:
  home: https://github.com/csyhuang/hn2016_falwa
  license: MIT
  license_family: MIT
  summary: Finite amplitude local wave activity package
```

I first created a conda environment `test_MDTF_base` from the [MDTF base environment](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/src/conda/env_base.yml), then I did:

```bash
conda build .
```
and a compatibility issue between the specific `numpy` version used and `setuptools` arises:

```
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                          
failed to parse packages from exception: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
setuptools -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.11,<3.12.0a0|>=3.5,<3.6.0a0']
numpy==1.22.3 -> mkl_fft[version='>=1.3.1,<2.0a0'] -> python[version='2.7.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
python=3.7
numpy==1.22.3 -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.11,<3.12.0a0']
setuptools -> certifi[version='>=2016.9.26'] -> python[version='2.7.*|3.6.*']

Package tzdata conflicts for:
setuptools -> python[version='>=3.9,<3.10.0a0'] -> tzdata
numpy==1.22.3 -> python[version='>=3.10,<3.11.0a0'] -> tzdata
```
